---
title: "Gene ID conversion"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

The bioconductor organism annotation packages provide sources for converting between different
gene ID types:

```{r}
library(org.Hs.eg.db)
ls(envir = asNamespace("org.Hs.eg.db"))
```

```{r}
genes = c("TP53", "MDM2")
```

1. convert to Entrez gene ID:

```{r}
eg = unlist(as.list(org.Hs.egSYMBOL2EG[genes]))
```

2. convert to ensembl gene ID

```{r}
en = unlist(as.list(org.Hs.egENSEMBL[eg]))
```

3. convert to Refseq ID

```{r}
refseq = as.list(org.Hs.egREFSEQ[eg])
sapply(refseq, function(x) x[1])
```


```{r}
convert_to_entrez_id = function(x, org_db = "org.Hs.eg.db") {
	if(is.matrix(x)) {
		map = cola:::guess_id_mapping(rownames(x), org_db = org_db)
		if(is.function(map)) {
		    new_rn = map(rownames(x))
		} else {
		    new_rn = map[rownames(x)]
		}
		l = is.na(new_rn)

		x = x[!l, , drop = FALSE]
		new_rn = new_rn[!l]

		x2 = do.call(rbind, tapply(1:nrow(x), new_rn, function(ind) {
			colMeans(x[ind, , drop = FALSE])
		}))
		return(x2)

	} else if(is.numeric(x)) {
		map = cola:::guess_id_mapping(names(x), org_db = org_db)
		x2 = x
		if(is.function(map)) {
		    names(x2) = map(names(x))
		} else {
		    names(x2) = map[names(x)]
		}
		x2 = x2[!is.na(names(x2))]
		x2 = tapply(x2, names(x2), mean)
		return(x2)
	} else {
	    map = cola:::guess_id_mapping(x, org_db = org_db)
	    if(is.function(map)) {
	        x2 = map(x)
	    } else {
	        x2 = map[x]
	    }
	    x2 = x2[!is.na(x2)]
	    x2 = unique(x2)
	    return(x2)
	}
}
```

```{r}
convert_to_entrez_id(genes)
convert_to_entrez_id(en)
```

```{r}
mat = matrix(rnorm(2*10), nrow = 2)
rownames(mat) = genes
convert_to_entrez_id(mat)
```

```{r}
x = rnorm(2)
names(x) = genes
convert_to_entrez_id(x)
```
