---
title: "The list of R markdown documents"
output:
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---


GitHub repo: https://github.com/jokergoo/GSEA_teaching


## Datasets

- [diff_gene.txt](diff_gene.txt)
- [background_gene.txt](background_gene.txt)
- [E-GEOD-101794-analytics.tsv](E-GEOD-101794-analytics.tsv)
- [P53.cls](P53.cls)
- [P53_collapsed_symbols.gct](P53_collapsed_symbols.gct)
- [p53.RData](p53.RData)
- [h.all.v7.5.1.symbols.gmt](h.all.v7.5.1.symbols.gmt)

## Markdown documents

### Day 1

Gene set databases

- [day1_process_GO.html](day1_process_GO.html)
- [day1_msigdbr.html](day1_msigdbr.html)
- [day1_biomart.html](day1_biomart.html)
- [day1_kegg.html](day1_kegg.html)
- [day1_Reactome.html](day1_Reactome.html)
- [day1_UniProtKeywords.html](day1_UniProtKeywords.html)
- [day1_gene_id.html](day1_gene_id.html)
- [day1_go_excise_solutions.R](day1_go_excise_solutions.R)


### Day 2

ORA

- [day2_ora_example.html](day2_ora_example.html)
- [day2_clusterProfiler_ora.html](day2_clusterProfiler_ora.html)
- [day2_ora_exercise.html](day2_ora_exercise.html)

GSEA tool

- [day2_gsea_example.html](day2_gsea_example.html)
- [day2_clusterProfiler_gsea.html](day2_clusterProfiler_gsea.html)
- [day2_gsea_exercise.html](day2_gsea_exercise.html)


Compare ORA and GSEA

- [day2_compare_ORA_GSEA.html](day2_compare_ORA_GSEA.html)


GSEA framework

- [day2_tiny_GSEA_framework.html](day2_tiny_GSEA_framework.html)
- [day2_EnrichmentBrowser.html](day2_EnrichmentBrowser.html)
- [day2_gsea_framework_solution](day2_gsea_framework_solution.html)

### Day 3

On specific data types

- [day3_rGREAT.html](day3_rGREAT.html)
- [day3_goseq.html](day3_goseq.html)

Single sample GSEA

- [day3_GSVA.html](day3_GSVA.html)

Topology-based pathway enrichment

- [day3_topology_based_pathway_enrichment.html](day3_topology_based_pathway_enrichment.html)

Ensemble of multiple GSEA results

- [day3_piano.html](day3_piano.html)

### Day 4

- [day4_visualization.html](day4_visualization.html)
- [day4_simplifyEnrichment.html](day4_simplifyEnrichment.html)

